# Generated by Django 6.0.1 on 2026-01-23 15:44

from django.db import migrations, models


def remove_duplicates(apps, schema_editor):
    Quote = apps.get_model('api', 'Quote')
    # Logic to find and delete duplicates
    for text in Quote.objects.values_list('text', flat=True).distinct():
        duplicates = Quote.objects.filter(text=text)
        if duplicates.count() > 1:
            # Keep the first one, delete others
            first_id = duplicates.first().id
            duplicates.exclude(id=first_id).delete()


def revert_change(apps, schema_editor):
    """
    As data was deleted during the forward migration to satisfy the UNIQUE 
    constraint, it cannot be restored. We pass to allow the schema rollback.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        # 1. We fix the data FIRST
        migrations.RunPython(remove_duplicates, revert_change),
        # 2. THEN we apply the unique constraint
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(unique=True),
        ),
    ]
